spring:
  jackson:
    time-zone: UTC

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

benchmark:
  feedback:
    direct-base-url: ${FEEDBACK_DIRECT_URL:http://localhost:8091}
    service-id: feedbackservice
    instance-endpoint: /api/v1/discovery/instance
