spring.application.name=eurekaserver
server.port=8761

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.fail-fast=false

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
