spring.application.name=configserver
server.port=${CONFIG_SERVER_PORT:8888}

spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/central-config,file:./central-config

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always
