spring.application.name=userservice

server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.healthcheck.enabled=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/userdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:mysecretpassword}
spring.datasource.driver-class-name=org.postgresql.Driver
db.admin.username=${DB_ADMIN_USERNAME:${spring.datasource.username}}
db.admin.password=${DB_ADMIN_PASSWORD:${spring.datasource.password}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.time-zone=UTC

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

benchmark.feedback.direct-base-url=${FEEDBACK_DIRECT_URL:http://localhost:8091}
benchmark.feedback.service-id=feedbackservice
benchmark.feedback.instance-endpoint=/api/v1/discovery/instance
